config/routes.rb
DemoApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :schools 
  resources :colleges

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete # invokes HTTP DELETE request
  
  root to: 'static_pages#home'
  match '/help',	to: 'static_pages#help'
  match '/about',	to: 'static_pages#about'
  match '/contact',	to: 'static_pages#contact'
  match '/signup',	to: 'users#new'

end

app/models/school.rb
# == Schema Information
#
# Table name: schools
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  avg        :decimal(, )
#  total      :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class School < ActiveRecord::Base
  attr_accessible :name, :avg, :total
  
  validates :name, presence: true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	before_filter :signed_in_user, only: [:index, :show]
	
  def show
    @college = School.find(params[:id])
  end
  
  def index
  	if params[:search]
  		@colleges = School.where('schools.name LIKE ?',"%#{params[:search]}%").paginate(page: params[:page])
  	else
  		@colleges = School.paginate(page: params[:page])
  	end
  end
end

app/views/schools/_school.html.erb
<li>
  <%= link_to school.name, school %>
</li>

app/views/schools/index.html.erb
<% provide(:title, 'All colleges') %>
<h1>All colleges</h1>

<div class="search">
	<%= form_tag schools_path, :method => 'get' do %>
			<%= text_field_tag :search, params[:search], placeholder: "Search for a college..." %>
			<%= submit_tag "Search", :name => nil, class: "btn btn-large btn-primary" %>
	<% end %>
</div>

<%= will_paginate @colleges %>

<ul class="colleges">
  <%= render @colleges %>
</ul>

<%= will_paginate @colleges %>

app/views/schools/show.html.erb
<% provide(:title, @college.name) %>
<div class="college">
	<h1>
		<%= @college.name %>
	</h1>
	<h3>
		Rate My Professors		
	</h3>
  <h4><em>Average:</em> <%= @college.avg %></h4>
	<h4><em>Total:</em> <%= @college.total %></h4>
</div>